# this is the base docker compose
#
# run production stack (arenaxr; extend docker-compose.yaml):
#    docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d
#
# run staging stack (dev1; extend docker-compose.yaml):
#    docker-compose -f docker-compose.yaml -f docker-compose.staging.yaml up -d
#
# run local development stack (does not extend docker-compose.yaml):
#    docker-compose -f docker-compose.localdev.yaml up -d
#
# run demo stack (does not extend docker-compose.yaml):
#    docker-compose -f docker-compose.demo.yaml up -d

version: "3.9"

services:
  arena-web:
    build: ./arena-web-core
    container_name: arena-web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./conf:/usr/share/nginx/html/conf:ro
    depends_on:
      - mqtt
      - arena-persist
      - store
      - arena-account
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db:rw
      - ./data/backup:/backup:rw
    restart: unless-stopped

  arena-persist:
    build: ./arena-persist
    container_name: arena-persist
    user: "node"
    volumes:
      - ./conf/persist-config.json:/home/node/app/config.json:ro
      - ./data/keys/jwt.public.pem:/home/node/app/pubsubkey.pub:ro
    command: "npm run start"
    depends_on:
      - mongodb
      - mqtt
    restart: unless-stopped

  arena-account:
    build: ./arena-account
    container_name: arena-account
    ports:
      - "8000:8000" 
    volumes:
      - ./conf/account-settings.py:/usr/src/app/arena_account/settings.py:ro
      - account-static-content:/usr/src/app/static
      - ./data/account:/usr/src/app/db
      - ./data/keys/jwt.priv.pem:/home/node/app/pubsubkey.pem:ro
    env_file:
      - .env
      - secret.env
    depends_on:
      - arena-persist
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: arena-broker
    volumes:
      - ./conf/mosquitto-anon.conf:/mosquitto/config/mosquitto.conf:ro
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/keys/jwt.public.der:/pubsubkey.der:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
    ports:
      - 8083:8083/tcp
      - 8883:8883/tcp
    restart: unless-stopped

  store:
    image: filebrowser/filebrowser:latest
    container_name: arena-store
    volumes:
      - ./conf/store-config.json:/.filebrowser.json:ro
      - ./store-branding:/arena-store/frontend/arena-branding:ro
      - ./store:/srv-files:rw
      - ./data/arena-store:/arena-store/data:rw
    restart: unless-stopped

volumes:
  account-static-content:

